import {
  BedDouble,
  ArrowRight,
  Home,
  Film,
  List,
  Plus,
  ChevronDown,
  ChevronUp,
  Check,
  Trash,
  MoreVertical,
  Edit,
  ChevronLeft,
  ChevronRight,
  Loader2,
  User,
  Upload,
  Save,
  Tag,
  Settings,
  CalendarDays,
  PhoneCall,
  ArrowRightIcon,
  Play,
  Mail,
  MapPin,
  Quote,
  ArrowDownIcon,
  ChevronUpIcon,
  Facebook,
  Linkedin,
  Twitter,
  Instagram,
  Youtube,
  AirVent,
  Wifi,
  EggFried,
  RectangleVertical,
  Waves,
  Microwave,
  ShowerHead,
  Bath,
  Refrigerator,
  Tv,
  Scroll,
  Menu,
  X,
  Users2,
  Image,
  Wrench,
  MessageCircle,
} from "lucide-react";

export const Icons = {
  user: User,
  room: BedDouble,
  logo: Home,
  arrowright: ArrowRight,
  category: List,
  gallery: Film,
  add: Plus,
  down: ChevronDown,
  up: ChevronUp,
  check: Check,
  delete: Trash,
  menu: MoreVertical,
  edit: Edit,
  left: ChevronLeft,
  right: ChevronRight,
  spinner: Loader2,
  upload: Upload,
  save: Save,
  tags: Tag,
  setting: Settings,
  booking: CalendarDays,
  phone: PhoneCall,
  arrowRight: ArrowRightIcon,
  arrowDown: ArrowDownIcon,
  play: Play,
  mail: Mail,
  mapPin: MapPin,
  quote: Quote,
  facebook: Facebook,
  linkedin: Linkedin,
  twitter: Twitter,
  instagram: Instagram,
  youtube: Youtube,
  airConditioner: AirVent,
  wifi: Wifi,
  breakfast: EggFried,
  towel: RectangleVertical,
  swimming: Waves,
  oven: Microwave,
  shower: ShowerHead,
  bathTub: Bath,
  refrigerator: Refrigerator,
  tv: Tv,
  testimonials: Scroll,
  hamburger: Menu,
  close: X,
  team: Users2,
  banner: Image,
  services: Wrench,
  arrowUp: ChevronUpIcon,
  message: MessageCircle,
};
